### ISSUE TITLE
error "AttributeError: 'VCD' object has no attribute 'data'"

### ISSUE THREAD

**Issue by pncanas333** [Vicomtech/video-content-description-VCD#26]
I get this error when I try to load a VCD v5.0 (OpenLabel) file with the VCDv4.3 library. 

Versions don't match. I know this is not a common situation, but I'm sharing it in case someone is trying to identify the cause of this error. 

Solution: Update the library VCDv4.3 to v5.0.

**Comment by marcosnietodoncel** [comment]
That is right.
An Exception has been added to core.py.
This feature is available in branch feature/projection, and will be available in next release.
